### ISSUE TITLE
Bad Syntax  

### ISSUE THREAD

**Issue by thapakazi** [rhoit/my-config#3]
dai, this [line](https://github.com/rhoit/my-config/blob/master/tmux/Makefile#L4) spit out error :see_no_evil: 

demo:
![screenshot-20160728-22 09 23](https://cloud.githubusercontent.com/assets/1695906/17220719/378c9144-5510-11e6-9556-1508971e255f.png)

**Comment by rhoit** [comment]
Should have worked, tested in mine, 

![screenshot46](https://cloud.githubusercontent.com/assets/1684754/17236297/c547373a-5567-11e6-822e-d5ef9a374646.png)

as in code of.. seems lot similar to this.
https://github.com/rhoit/my-config/blob/master/tmux/Makefile

**Comment by krazedkrish** [comment]
:+1:
